#### Working with CSV, JSON and EXCEL Files
##### Pandas

In [1]:
#--------------------------------------------
# Import the Pandas libraries
#--------------------------------------------
import pandas as pd

In [2]:
df1 = pd.DataFrame([[2,4,6], [10,20,30]]) # 2,4,6 if first row, 10,20,30 is second row

In [3]:
df1

    0   1   2
0   2   4   6
1  10  20  30

In [13]:
df1 = pd.DataFrame([[2,4,6], [10,20,30]], columns=['Price', 'Age', 'Value'])
df1

   Price  Age  Value
0      2    4      6
1     10   20     30

In [8]:
df2 = pd.DataFrame([[2,4,6], [10,20,30]], columns=['Price', 'Age', 'Value'], index=['1st', '2nd'])
df2

     Price  Age  Value
1st      2    4      6
2nd     10   20     30

In [12]:
df2 = pd.DataFrame([{'Name':'John', 'Surname':'Johns'},{'Name':'Jack'}])
df2

   Name Surname
0  John   Johns
1  Jack     NaN

In [14]:
dir(df1)

['Age',
 'Price',
 'T',
 'Value',
 '_AXIS_ALIASES',
 '_AXIS_IALIASES',
 '_AXIS_LEN',
 '_AXIS_NAMES',
 '_AXIS_NUMBERS',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_add_numeric_operations',
 '_add_series_or_dataframe_operations',
 '_agg_by_level',
 '_agg_examples_doc',
 '_agg_summary_and_see_also_doc',
 '_aggregate',
 '_aggregate_multiple_funcs',
 '_align_frame',
 '_align_series',
 '_box_col_values',
 '_box_item_values',
 '_builtin_table',
 '_check_inplace_setting',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_combine_frame',
 '_combine_match_index',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_axes_dict_from',
 '_construct_axes_from_arguments',
 '_construct_result',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_sliced',
 '_convert',
 '_count_level',
 '_create_indexer',
 '_cython_table',
 '_deprecations',
 '_dir_additions',
 '_dir_deletions',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_from_arrays',
 '_from_axes',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cacher',
 '_get_cleaned_column_resolvers',
 '_get_cython_func',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_gotitem',
 '_iget_item_cache',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_internal_get_values',
 '_internal_names',
 '_internal_names_set',
 '_is_builtin_func',
 '_is_cached',
 '_is_copy',
 '_is_datelike_mixed_type',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_numeric_mixed_type',
 '_is_view',
 '_ix',
 '_ixs',
 '_join_compat',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_needs_reindex_multi',
 '_obj_with_exclusions',
 '_protect_consolidate',
 '_reduce',
 '_reindex_axes',
 '_reindex_columns',
 '_reindex_index',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_selected_obj',
 '_selection',
 '_selection_list',
 '_selection_name',
 '_series',
 '_set_as_cached',
 '_set_axis',
 '_set_axis_name',
 '_set_is_copy',
 '_set_item',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_setup_axes',
 '_slice',
 '_stat_axis',
 '_stat_axis_name',
 '_stat_axis_number',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_try_aggregate_string_function',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 '_xs',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'append',
 'apply',
 'applymap',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'floordiv',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isin',
 'isna',
 'isnull',
 'items',
 'iteritems',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lookup',
 'lt',
 'mad',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'slice_shift',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tshift',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'values',
 'var',
 'where',
 'xs']

In [15]:
df1.mean()

Price     6.0
Age      12.0
Value    18.0
dtype: float64

In [16]:
df1.mean().mean()

12.0

In [17]:
type(df1.mean())

pandas.core.series.Series

In [20]:
from bs4 import BeautifulSoup
import requests

In [21]:
r=requests.get("http://en.wikipedia.org/wiki/Eagle")
print(r.content)

b'<!DOCTYPE html>\n<html class="client-nojs" lang="en" dir="ltr">\n<head>\n<meta charset="UTF-8"/>\n<title>Eagle - Wikipedia</title>\n<script>document.documentElement.className="client-js";RLCONF={"wgBreakFrames":!1,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"X-H4sgpAADkAAC@2iFwAAADK","wgCSPNonce":!1,"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":!1,"wgNamespaceNumber":0,"wgPageName":"Eagle","wgTitle":"Eagle","wgCurRevisionId":997485620,"wgRevisionId":997485620,"wgArticleId":37602,"wgIsArticle":!0,"wgIsRedirect":!1,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["CS1 German-language sources (de)","Webarchive template wayback links","Articles with short description","Short description is different from Wikidata","Use dmy dates from May 2015","Articles with \'species\' microformats","Wikipedia articles needing clarification from November 2020","Articles containing Latin-language text",\n"Articles containing French-language text","Articles containing Old English (ca. 450-1100)-language text","Articles containing Greek-language text","Articles containing Russian-language text","Articles containing Welsh-language text","All articles with unsourced statements","Articles with unsourced statements from December 2012","Articles needing additional references from July 2016","All articles needing additional references","Commons category link is locally defined","Wikipedia articles incorporating a citation from the New International Encyclopedia","Wikipedia articles with GND identifiers","Wikipedia articles with LCCN identifiers","Wikipedia articles with NARA identifiers","Wikipedia articles with NDL identifiers","Eagles","Accipitridae","Apex predators","Bird common names","Vultures","National symbols of Armenia","National symbols of Austria","National symbols of the Czech Republic","National symbols of Germany","National symbols of Ghana","National symbols of Liechtenstein",\n"National symbols of Mexico","National symbols of Nigeria","National symbols of Poland","National symbols of Romania","National symbols of Serbia","National symbols of Spain","National symbols of Syria","National symbols of Yemen","National symbols of Zambia"],"wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"Eagle","wgRelevantArticleId":37602,"wgIsProbablyEditable":!0,"wgRelevantPageIsProbablyEditable":!0,"wgRestrictionEdit":[],"wgRestrictionMove":[],"wgMediaViewerOnClick":!0,"wgMediaViewerEnabledByDefault":!0,"wgPopupsReferencePreviews":!1,"wgPopupsConflictsWithNavPopupGadget":!1,"wgPopupsConflictsWithRefTooltipsGadget":!0,"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":!0,"nearby":!0,"watchlist":!0,"tagline":!1},"wgWMESchemaEditAttemptStepOversample":!1,"wgULSCurrentAutonym":"English","wgNoticeProject":"wikipedia",\n"wgCentralAuthMobileDomain":!1,"wgEditSubmitButtonLabelPublish":!0,"wgULSPosition":"interlanguage","wgWikibaseItemId":"Q2092297"};RLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","noscript":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.cite.styles":"ready","ext.categoryTree.styles":"ready","skins.vector.styles.legacy":"ready","jquery.makeCollapsible.styles":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","ext.wikimediaBadges":"ready","wikibase.client.init":"ready"};RLPAGEMODULES=["ext.cite.ux-enhancements","ext.categoryTree","site","mediawiki.page.ready","jquery.makeCollapsible","mediawiki.toc","skins.vector.legacy.js","ext.gadget.ReferenceTooltips","ext.gadget.charinsert","ext.gadget.extra-toolbar-buttons","ext.gadget.refToolbar","ext.gadget.switcher","ext.centralauth.centralautologin","mmv.head","mmv.bootstrap.autostart","ext.popups",\n"ext.visualEditor.desktopArticleTarget.init","ext.visualEditor.targetLoader","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.compactlinks","ext.uls.interface","ext.cx.eventlogging.campaigns","ext.centralNotice.geoIP","ext.centralNotice.startUp"];</script>\n<script>(RLQ=window.RLQ||[]).push(function(){mw.loader.implement("user.options@1hzgi",function($,jQuery,require,module){/*@nomin*/mw.user.tokens.set({"patrolToken":"+\\\\","watchToken":"+\\\\","csrfToken":"+\\\\"});\n});});</script>\n<link rel="stylesheet" href="/w/load.php?lang=en&amp;modules=ext.categoryTree.styles%7Cext.cite.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediaBadges%7Cjquery.makeCollapsible.styles%7Cskins.vector.styles.legacy%7Cwikibase.client.init&amp;only=styles&amp;skin=vector"/>\n<script async="" src="/w/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector"></script>\n<meta name="ResourceLoaderDynamicStyles" content=""/>\n<link rel="stylesheet" href="/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector"/>\n<meta name="generator" content="MediaWiki 1.36.0-wmf.22"/>\n<meta name="referrer" content="origin"/>\n<meta name="referrer" content="origin-when-crossorigin"/>\n<meta name="referrer" content="origin-when-cross-origin"/>\n<meta property="og:image" content="https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/%C3%81guila_calva.jpg/1200px-%C3%81guila_calva.jpg"/>\n<link rel="preconnect" href="//upload.wikimedia.org"/>\n<link rel="alternate" media="only screen and (max-width: 720px)" href="//en.m.wikipedia.org/wiki/Eagle"/>\n<link rel="alternate" type="application/x-wiki" title="Edit this page" href="/w/index.php?title=Eagle&amp;action=edit"/>\n<link rel="edit" title="Edit this page" href="/w/index.php?title=Eagle&amp;action=edit"/>\n<link rel="apple-touch-icon" href="/static/apple-touch/wikipedia.png"/>\n<link rel="shortcut icon" href="/static/favicon/wikipedia.ico"/>\n<link rel="search" type="application/opensearchdescription+xml" href="/w/opensearch_desc.php" title="Wikipedia (en)"/>\n<link rel="EditURI" type="application/rsd+xml" href="//en.wikipedia.org/w/api.php?action=rsd"/>\n<link rel="license" href="//creativecommons.org/licenses/by-sa/3.0/"/>\n<link rel="canonical" href="https://en.wikipedia.org/wiki/Eagle"/>\n<link rel="dns-prefetch" href="//login.wikimedia.org"/>\n<link rel="dns-prefetch" href="//meta.wikimedia.org" />\n</head>\n<body class="mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject mw-editable page-Eagle rootpage-Eagle skin-vector action-view skin-vector-legacy"><div id="mw-page-base" class="noprint"></div>\n<div id="mw-head-base" class="noprint"></div>\n<div id="content" class="mw-body" role="main">\n\t<a id="top"></a>\n\t<div id="siteNotice" class="mw-body-content"><!-- CentralNotice --></div>\n\t<div class="mw-indicators mw-body-content">\n\t</div>\n\t<h1 id="firstHeading" class="firstHeading" lang="en">Eagle</h1>\n\t<div id="bodyContent" class="mw-body-content">\n\t\t<div id="siteSub" class="noprint">From Wikipedia, the free encyclopedia</div>\n\t\t<div id="contentSub"></div>\n\t\t<div id="contentSub2"></div>\n\t\t\n\t\t<div id="jump-to-nav"></div>\n\t\t<a class="mw-jump-link" href="#mw-head">Jump to navigation</a>\n\t\t<a class="mw-jump-link" href="#searchInput">Jump to search</a>\n\t\t<div id="mw-content-text" lang="en" dir="ltr" class="mw-content-ltr"><div class="mw-parser-output"><div class="shortdescription nomobile noexcerpt noprint searchaux" style="display:none">Large carnivore bird</div>\n<div role="note" class="hatnote navigation-not-searchable">This article is about the bird. For other uses, see <a href="/wiki/Eagle_(disambiguation)" class="mw-disambig" title="Eagle (disambiguation)">Eagle (disambiguation)</a> and <a href="/wiki/Eagles_(disambiguation)" class="mw-disambig" title="Eagles (disambiguation)">Eagles (disambiguation)</a>.</div>\n<p class="mw-empty-elt">\n\n</p>\n<table class="infobox biota" style="text-align: left; width: 200px; font-size: 100%">\n\n<tbody><tr>\n<th colspan="2" style="text-align: center; background-color: rgb(235,235,210)">Eagle\n</th></tr>\n<tr>\n<td colspan="2" style="text-align: center"><a href="/wiki/File:%C3%81guila_calva.jpg" class="image"><img alt="\xc3\x81guila calva.jpg" src="//upload.wikimedia.org/wikipedia/commons/thumb/1/19/%C3%81guila_calva.jpg/220px-%C3%81guila_calva.jpg" decoding="async" width="220" height="156" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/1/19/%C3%81guila_calva.jpg/330px-%C3%81guila_calva.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/1/19/%C3%81guila_calva.jpg/440px-%C3%81guila_calva.jpg 2x" data-file-width="1911" data-file-height="1356" /></a>\n</td></tr>\n<tr>\n<td colspan="2" style="text-align: center; font-size: 88%"><a href="/wiki/Bald_eagle" title="Bald eagle">Bald eagle</a>\n</td></tr>\n\n\n\n\n\n<tr>\n<th colspan="2" style="min-width:15em; text-align: center; background-color: rgb(235,235,210)"><a href="/wiki/Taxonomy_(biology)" title="Taxonomy (biology)">Scientific classification</a>\n</th></tr>\n\n\n\n\n\n\n\n\n\n<tr>\n<td>Kingdom:\n</td>\n<td><div style="display:inline" class="kingdom"><a href="/wiki/Animalia" class="mw-redirect" title="Animalia">Animalia</a></div>\n</td></tr>\n\n\n\n\n\n\n\n\n\n<tr>\n<td>Phylum:\n</td>\n<td><div style="display:inline" class="phylum"><a href="/wiki/Chordata" class="mw-redirect" title="Chordata">Chordata</a></div>\n</td></tr>\n\n\n\n\n\n\n\n\n\n\n\n\n\n<tr>\n<td>Class:\n</td>\n<td><div style="display:inline" class="class"><a href="/wiki/Aves" class="mw-redirect" title="Aves">Aves</a></div>\n</td></tr>\n\n\n\n\n\n\n\n\n\n<tr>\n<td>Order:\n</td>\n<td><div style="display:inline" class="order"><a href="/wiki/Accipitriformes" title="Accipitriformes">Accipitriformes</a></div>\n</td></tr>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<tr>\n<td>Family:\n</td>\n<td><div style="display:inline" class="family"><a href="/wiki/Accipitridae" title="Accipitridae">Accipitridae</a></div>\n</td></tr>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<tr>\n<th colspan="2" style="text-align: center; background-color: rgb(235,235,210)">Species\n</th></tr>\n<tr>\n<td colspan="2" style="text-align: left">\n<p>See <a href="#Species">text</a>.\n</p>\n</td></tr>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n</tbody></table>\n<p><b>Eagle</b> is the common name for many large <a href="/wiki/Bird_of_prey" title="Bird of prey">birds of prey</a> of the family <a href="/wiki/Accipitridae" title="Accipitridae">Accipitridae</a>. Eagles belong to several groups of <a href="/wiki/Genus" title="Genus">genera</a>, some of which are closely related. Most of the 60 species of eagle are from Eurasia and Africa.<sup id="cite_ref-1" class="reference"><a href="#cite_note-1">&#91;1&#93;</a></sup> Outside this area, just 14 species can be found\xe2\x80\x942 in North America, 9 in Central and South America, and 3 in Australia. It is nicknamed the king of all birds.\n</p>\n<div id="toc" class="toc" role="navigation" aria-labelledby="mw-toc-heading"><input type="checkbox" role="button" id="toctogglecheckbox" class="toctogglecheckbox" style="display:none" /><div class="toctitle" lang="en" dir="ltr"><h2 id="mw-toc-heading">Contents</h2><span class="toctogglespan"><label class="toctogglelabel" for="toctogglecheckbox"></label></span></div>\n<ul>\n<li class="toclevel-1 tocsection-1"><a href="#Description"><span class="tocnumber">1</span> <span class="toctext">Description</span></a></li>\n<li class="toclevel-1 tocsection-2"><a href="#Distribution"><span class="tocnumber">2</span> <span class="toctext">Distribution</span></a></li>\n<li class="toclevel-1 tocsection-3"><a href="#Groups"><span class="tocnumber">3</span> <span class="toctext">Groups</span></a>\n<ul>\n<li class="toclevel-2 tocsection-4"><a href="#Fish_eagles"><span class="tocnumber">3.1</span> <span class="toctext">Fish eagles</span></a></li>\n<li class="toclevel-2 tocsection-5"><a href="#Booted_eagles"><span class="tocnumber">3.2</span> <span class="toctext">Booted eagles</span></a></li>\n<li class="toclevel-2 tocsection-6"><a href="#Snake_eagles"><span class="tocnumber">3.3</span> <span class="toctext">Snake eagles</span></a></li>\n<li class="toclevel-2 tocsection-7"><a href="#Harpy_eagles"><span class="tocnumber">3.4</span> <span class="toctext">Harpy eagles</span></a></li>\n</ul>\n</li>\n<li class="toclevel-1 tocsection-8"><a href="#Species"><span class="tocnumber">4</span> <span class="toctext">Species</span></a></li>\n<li class="toclevel-1 tocsection-9"><a href="#In_culture"><span class="tocnumber">5</span> <span class="toctext">In culture</span></a>\n<ul>\n<li class="toclevel-2 tocsection-10"><a href="#Etymology"><span class="tocnumber">5.1</span> <span class="toctext">Etymology</span></a></li>\n<li class="toclevel-2 tocsection-11"><a href="#Religion_and_folklore"><span class="tocnumber">5.2</span> <span class="toctext">Religion and folklore</span></a></li>\n<li class="toclevel-2 tocsection-12"><a href="#Heraldry"><span class="tocnumber">5.3</span> <span class="toctext">Heraldry</span></a></li>\n</ul>\n</li>\n<li class="toclevel-1 tocsection-13"><a href="#Notes"><span class="tocnumber">6</span> <span class="toctext">Notes</span></a></li>\n<li class="toclevel-1 tocsection-14"><a href="#References"><span class="tocnumber">7</span> <span class="toctext">References</span></a></li>\n<li class="toclevel-1 tocsection-15"><a href="#Further_reading"><span class="tocnumber">8</span> <span class="toctext">Further reading</span></a></li>\n<li class="toclevel-1 tocsection-16"><a href="#External_links"><span class="tocnumber">9</span> <span class="toctext">External links</span></a></li>\n</ul>\n</div>\n\n<h2><span class="mw-headline" id="Description">Description</span><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=Eagle&amp;action=edit&amp;section=1" title="Edit section: Description">edit</a><span class="mw-editsection-bracket">]</span></span></h2>\n<p>Eagles are large, powerfully built <a href="/wiki/Birds_of_prey" class="mw-redirect" title="Birds of prey">birds of prey</a>, with heavy heads and beaks. Even the smallest eagles, such as the <a href="/wiki/Booted_eagle" title="Booted eagle">booted eagle</a> (<i>Aquila pennata</i>), which is comparable in size to a <a href="/wiki/Common_buzzard" title="Common buzzard">common buzzard</a> (<i>Buteo buteo</i>) or <a href="/wiki/Red-tailed_hawk" title="Red-tailed hawk">red-tailed hawk</a> (<i>B. jamaicensis</i>), have relatively longer and more evenly broad wings, and more direct, faster flight \xe2\x80\x93 despite the reduced size of aerodynamic feathers. Most eagles are larger than any other raptors apart from some <a href="/wiki/Vulture" title="Vulture">vultures</a>. The smallest species of eagle is the <a href="/wiki/South_Nicobar_serpent_eagle" class="mw-redirect" title="South Nicobar serpent eagle">South Nicobar serpent eagle</a> (<i>Spilornis klossi</i>), at 450&#160;g (1&#160;lb) and 40&#160;cm (16&#160;in). The largest species are discussed below. Like all birds of prey, eagles have very large, hooked <a href="/wiki/Beak" title="Beak">beaks</a> for ripping flesh from their prey, strong, muscular legs, and powerful <a href="/wiki/Claw" title="Claw">talons</a>. The beak is typically heavier than that of most other birds of prey. Eagles\' eyes are extremely powerful. It is estimated that the <a href="/wiki/Martial_eagle" title="Martial eagle">martial eagle</a>, whose eye is more than twice as long<sup class="noprint Inline-Template" style="margin-left:0.1em; white-space:nowrap;">&#91;<i><a href="/wiki/Wikipedia:Please_clarify" title="Wikipedia:Please clarify"><span title="&quot;long&quot; is a strange word to use in relation to an eye (November 2020)">clarification needed</span></a></i>&#93;</sup> as a human eye, has a <a href="/wiki/Visual_acuity" title="Visual acuity">visual acuity</a> 3.0 to 3.6 times that of humans. This acuity enables eagles to spot potential prey from a very long distance.<sup id="cite_ref-2" class="reference"><a href="#cite_note-2">&#91;2&#93;</a></sup> This keen eyesight is primarily attributed to their extremely large pupils which ensure minimal <a href="/wiki/Diffraction" title="Diffraction">diffraction</a> (scattering) of the incoming light. The female of all known species of eagles is larger than the male.<sup id="cite_ref-3" class="reference"><a href="#cite_note-3">&#91;3&#93;</a></sup><sup id="cite_ref-Grambo2003_4-0" class="reference"><a href="#cite_note-Grambo2003-4">&#91;4&#93;</a></sup>\n</p><p>Eagles normally build their nests, called <a href="/wiki/Bird_nest" title="Bird nest">eyries</a>, in tall trees or on high cliffs. Many species lay two eggs, but the older, larger chick frequently kills its younger sibling once it has hatched. The dominant chick tends to be a female, as they are bigger than the male. The parents take no action to stop the killing.<sup id="cite_ref-gambo_5-0" class="reference"><a href="#cite_note-gambo-5">&#91;5&#93;</a></sup><sup id="cite_ref-stinson_6-0" class="reference"><a href="#cite_note-stinson-6">&#91;6&#93;</a></sup>\n</p><p>Due to the size and power of many eagle species, they are ranked at the top of the food chain as <a href="/wiki/Apex_predator" title="Apex predator">apex predators</a> in the avian world. The type of prey varies by genus. The <i><a href="/wiki/Haliaeetus" class="mw-redirect" title="Haliaeetus">Haliaeetus</a></i> and <i><a href="/wiki/Ichthyophaga" class="mw-redirect" title="Ichthyophaga">Ichthyophaga</a></i> eagles prefer to capture fish, though the species in the former often capture various animals, especially other <a href="/wiki/Water_bird" title="Water bird">water birds</a>, and are powerful <a href="/wiki/Kleptoparasitism" title="Kleptoparasitism">kleptoparasites</a> of other birds. The snake and serpent eagles of the genera <i><a href="/wiki/Circaetus" title="Circaetus">Circaetus</a></i>, <i><a href="/wiki/Bateleur" title="Bateleur">Terathopius</a></i>, and <i><a href="/wiki/Spilornis" title="Spilornis">Spilornis</a></i> predominantly prey on the great diversity of <a href="/wiki/Snake" title="Snake">snakes</a> found in the tropics of Africa and Asia. The eagles of the genus <i><a href="/wiki/Aquila_(genus)" title="Aquila (genus)">Aquila</a></i> are often the top birds of prey in open habitats, taking almost any medium-sized <a href="/wiki/Vertebrate" title="Vertebrate">vertebrate</a> they can catch. Where <i>Aquila</i> eagles are absent, other eagles, such as the <a href="/wiki/Buteoninae" title="Buteoninae">buteonine</a> <a href="/wiki/Black-chested_buzzard-eagle" title="Black-chested buzzard-eagle">black-chested buzzard-eagle</a> of South America, may assume the position of top raptorial predator in open areas. Many other eagles, including the species-rich genus <i><a href="/wiki/Spizaetus" title="Spizaetus">Spizaetus</a></i>, live predominantly in woodlands and forest. These eagles often target various arboreal or ground-dwelling mammals and birds, which are often unsuspectingly ambushed in such dense, knotty environments. Hunting techniques differ among the species and genera, with some individual eagles having engaged in quite varied techniques based on their environment and prey at any given time. Most eagles grab prey without landing and take flight with it, so the prey can be carried to a perch and torn apart.<sup id="cite_ref-RaptorsWorld_7-0" class="reference"><a href="#cite_note-RaptorsWorld-7">&#91;7&#93;</a></sup>\n</p><p>The <a href="/wiki/Bald_eagle" title="Bald eagle">bald eagle</a> is noted for having flown with the heaviest load verified to be carried by any flying bird, since one eagle flew with a 6.8&#160;kg (15&#160;lb) <a href="/wiki/Mule_deer" title="Mule deer">mule deer</a> fawn.<sup id="cite_ref-8" class="refere

In [43]:
#------------------------------------------------
# Set full file path names
#------------------------------------------------
folder_name = 'C:/Users/jrwel/Documents/Udemy/Python Mega Course/Data/Supermarket/'
file_name = 'supermarkets.csv'
csv_file = folder_name + file_name

file_name = 'supermarkets.json'
json_file = folder_name + file_name

file_name = 'supermarkets.xlsx'
xlsx_file = folder_name + file_name

file_name = 'supermarkets-commas.txt'
txt_comma_file = folder_name + file_name

file_name = 'supermarkets-semi-colons.txt'
txt_semi_file = folder_name + file_name

file_name = 'data.txt'
txt_data_file = folder_name + file_name

In [24]:
#------------------------------------------------
# Read .CSV file into a dataframe
#------------------------------------------------
df_supermarkets = pd.read_csv(csv_file)
df_supermarkets.head(10)

,ID,Address,City,State,Country,Name,Employees
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [25]:
#------------------------------------------------
# Listing files in current directory
#------------------------------------------------
import os
os.listdir()

['.ipynb_checkpoints',
 'App01-Thesauraus2.ipynb',
 'App01-Thesaurus.ipynb',
 'App01-Thesaurus03.ipynb',
 'App01-Thesaurus4.ipynb',
 'App01.py',
 'Practice Exam1.ipynb',
 'Program-00-The-Basics.ipynb',
 'Working with Pandas.ipynb']

In [27]:
#------------------------------------------------
# Read .CSV file into a dataframe
#------------------------------------------------
df1 = pd.read_csv(csv_file)
df1

,ID,Address,City,State,Country,Name,Employees
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [28]:
#------------------------------------------------
# Read .JSON file into a dataframe
#------------------------------------------------
df2 = pd.read_json(json_file)
df2

,ID,Address,City,State,Country,Name,Employees
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [29]:
#------------------------------------------------
# Read .XLSX file into a dataframe
#
# Note: Need to specify the sheet index
#       1st sheet is index 0
#------------------------------------------------
df3 = pd.read_excel(xlsx_file, sheet_name=0)
df3

,ID,Address,City,State,Country,Supermarket Name,Number of Employees
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [33]:
#------------------------------------------------
# Read .TXT file into a dataframe
#
# Note: Default separator is comma
#------------------------------------------------
df4 = pd.read_csv(txt_comma_file)
df4

,ID,Address,City,State,Country,Name,Employees
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [37]:
#------------------------------------------------
# Read .TXT file into a dataframe
#
# Note: Pass semi-colon (:) as separator
#------------------------------------------------
df5 = pd.read_csv(txt_semi_file, separator = ';')
#df5 = pd.read_csv(txt_semi_file)
df5

TypeError: parser_f() got an unexpected keyword argument 'separator'

In [41]:
pd.read_csv?

In [42]:
#------------------------------------------------
# Read .TXT file into a dataframe
#
# Note: Pass semi-colon (:) as separator ('sep')
#------------------------------------------------
df5 = pd.read_csv(txt_semi_file, sep = ';')
df5

,ID,Address,City,State,Country,Name,Employees
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [44]:
#------------------------------------------------
# Read .txt file into a dataframe
# With default header - uses first row
# of data as column names
#------------------------------------------------
df8 = pd.read_csv(txt_data_file)
df8

   1     3666 21st St  San Francisco          CA 94114  USA      Madeira   8
0  2   735 Dolores St  San Francisco          CA 94119  USA  Bready Shop  15
1  3      332 Hill St  San Francisco  California 94114  USA  Super River  25
2  4     3995 23rd St  San Francisco          CA 94114  USA   Ben's Shop  10
3  5  1056 Sanchez St  San Francisco        California  USA      Sanchez  12
4  6  551 Alvarado St  San Francisco          CA 94114  USA   Richvalley  20

In [46]:
#------------------------------------------------
# Read .txt file into a dataframe
# With no header attribute - uses 1, 2, 3, 
# etc. as column names
#------------------------------------------------
df8 = pd.read_csv(txt_data_file, header = None)
df8

   0                1              2                 3    4            5   6
0  1     3666 21st St  San Francisco          CA 94114  USA      Madeira   8
1  2   735 Dolores St  San Francisco          CA 94119  USA  Bready Shop  15
2  3      332 Hill St  San Francisco  California 94114  USA  Super River  25
3  4     3995 23rd St  San Francisco          CA 94114  USA   Ben's Shop  10
4  5  1056 Sanchez St  San Francisco        California  USA      Sanchez  12
5  6  551 Alvarado St  San Francisco          CA 94114  USA   Richvalley  20

In [47]:
#------------------------------------------------
# Read .txt file into a dataframe
# Assigning Column names when no
# header to is available
#------------------------------------------------
df8 = pd.read_csv(txt_data_file, header = None)
df8.columns = ["ID", "Address", "City", "ZIP", "Country", "Name", "Employees"]
df8

,ID,Address,City,ZIP,Country,Name,Employees
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

#### Working with individual items of a dataframe

In [49]:
#---------------------------------
# Assign new index
#
#  Note: df8 is unchanged
#---------------------------------
df8.set_index("ID")

,Address,City,ZIP,Country,Name,Employees
ID,,,,,,
1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
3,332 Hill St,San Francisco,California 94114,USA,Super River,25
4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [50]:
df8

,ID,Address,City,ZIP,Country,Name,Employees
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [ ]:
df9 = df8.set_index("ID")  # df9 is permanent new dataframe

In [51]:
#---------------------------------
# Assign new index 
# Use 'inplace=True' to change df8
#  Note: df8 is changed
#--------------------------------, inplace=True-
df8.set_index("ID", inplace=True)

In [52]:
df8

,Address,City,ZIP,Country,Name,Employees
ID,,,,,,
1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
3,332 Hill St,San Francisco,California 94114,USA,Super River,25
4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [53]:
#---------------------------------
# Assign new index 
# Use 'inplace=True' to change df8
#  Note: old ID index is lost
#---------------------------------
df8.set_index("Address", inplace=True)

In [54]:
df8

,City,ZIP,Country,Name,Employees
Address,,,,,
3666 21st St,San Francisco,CA 94114,USA,Madeira,8
735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
332 Hill St,San Francisco,California 94114,USA,Super River,25
3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
1056 Sanchez St,San Francisco,California,USA,Sanchez,12
551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [55]:
#---------------------------------
# Assign new index 
# Use 'inplace=True' to change df8
#  Note: Avoid lossing other index
#        with drop=False
#---------------------------------
df8.set_index("Name", inplace=True, drop=False)
df8

                      City               ZIP Country         Name  Employees
Name
Madeira      San Francisco          CA 94114     USA      Madeira          8
Bready Shop  San Francisco          CA 94119     USA  Bready Shop         15
Super River  San Francisco  California 94114     USA  Super River         25
Ben's Shop   San Francisco          CA 94114     USA   Ben's Shop         10
Sanchez      San Francisco        California     USA      Sanchez         12
Richvalley   San Francisco          CA 94114     USA   Richvalley         20

In [56]:
#------------------------------------------------
# Read .JSON file into a dataframe
#------------------------------------------------
df7 = pd.read_json(json_file)
df7

,ID,Address,City,State,Country,Name,Employees
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [57]:
df7=df7.set_index("Address")

In [59]:
df7.loc["735 Dolores St":"332 Hill St", "ID":"State"] # Locate all records with index (Address) between
                                                      # 735 Dolors St and 332 Hill St (Inclusive)

                ID           City             State
Address
735 Dolores St   2  San Francisco          CA 94119
332 Hill St      3  San Francisco  California 94114

In [60]:
df7.loc["735 Dolores St":"1056 Sanchez St", "ID":"State"] # From column ID to State

                 ID           City             State
Address
735 Dolores St    2  San Francisco          CA 94119
332 Hill St       3  San Francisco  California 94114
3995 23rd St      4  San Francisco          CA 94114
1056 Sanchez St   5  San Francisco        California

In [61]:
df7.loc["735 Dolores St", "State"] # Give value for 'State' for a specific record

'CA 94119'

In [62]:
#----------------------------------------------
#  Using iloc to get a slice of data
#
#  Note: for iloc the relative end bound
#        is exclusive. So [1:3] gets two rows
df7.iloc[1:3, 1:3] # the second [1:3] gets columns 1 and 2

                         City             State
Address
735 Dolores St  San Francisco          CA 94119
332 Hill St     San Francisco  California 94114

#### Modifying and merging dataframes

In [63]:
df7
#  Note:
#
#    Col0 = ID
#    Col1 = City
#    Col2 = State
#    Col3 = Country, etc

,ID,City,State,Country,Name,Employees
Address,,,,,,
3666 21st St,1,San Francisco,CA 94114,USA,Madeira,8
735 Dolores St,2,San Francisco,CA 94119,USA,Bready Shop,15
332 Hill St,3,San Francisco,California 94114,USA,Super River,25
3995 23rd St,4,San Francisco,CA 94114,USA,Ben's Shop,10
1056 Sanchez St,5,San Francisco,California,USA,Sanchez,12
551 Alvarado St,6,San Francisco,CA 94114,USA,Richvalley,20

In [65]:
df7.iloc[3,] # - Gets the 3rd row starting at row zero

ID                       4
City         San Francisco
State             CA 94114
Country                USA
Name            Ben's Shop
Employees               10
Name: 3995 23rd St, dtype: object

In [67]:
df7

,ID,City,State,Country,Name,Employees
Address,,,,,,
3666 21st St,1,San Francisco,CA 94114,USA,Madeira,8
735 Dolores St,2,San Francisco,CA 94119,USA,Bready Shop,15
332 Hill St,3,San Francisco,California 94114,USA,Super River,25
3995 23rd St,4,San Francisco,CA 94114,USA,Ben's Shop,10
1056 Sanchez St,5,San Francisco,California,USA,Sanchez,12
551 Alvarado St,6,San Francisco,CA 94114,USA,Richvalley,20

In [68]:
df7.drop("City", 1) # 1 means operate on the columns

                 ID             State Country         Name  Employees
Address
3666 21st St      1          CA 94114     USA      Madeira          8
735 Dolores St    2          CA 94119     USA  Bready Shop         15
332 Hill St       3  California 94114     USA  Super River         25
3995 23rd St      4          CA 94114     USA   Ben's Shop         10
1056 Sanchez St   5        California     USA      Sanchez         12
551 Alvarado St   6          CA 94114     USA   Richvalley         20

In [69]:
df7.drop("332 Hill St", 0) # 0 means operate on the row(s)

                 ID           City       State Country         Name  Employees
Address
3666 21st St      1  San Francisco    CA 94114     USA      Madeira          8
735 Dolores St    2  San Francisco    CA 94119     USA  Bready Shop         15
3995 23rd St      4  San Francisco    CA 94114     USA   Ben's Shop         10
1056 Sanchez St   5  San Francisco  California     USA      Sanchez         12
551 Alvarado St   6  San Francisco    CA 94114     USA   Richvalley         20

In [71]:
#df7.ix[3,4]

In [72]:
df7.drop(df7.columns[0:3], 1)

                Country         Name  Employees
Address
3666 21st St        USA      Madeira          8
735 Dolores St      USA  Bready Shop         15
332 Hill St         USA  Super River         25
3995 23rd St        USA   Ben's Shop         10
1056 Sanchez St     USA      Sanchez         12
551 Alvarado St     USA   Richvalley         20

In [73]:
df7.index

Index(['3666 21st St', '735 Dolores St', '332 Hill St', '3995 23rd St',
       '1056 Sanchez St', '551 Alvarado St'],
      dtype='object', name='Address')

In [74]:
df7.columns

Index(['ID', 'City', 'State', 'Country', 'Name', 'Employees'], dtype='object')

In [75]:
df7["Continent"] = ["North America"] # Will give error - need to pass a list with exact number of rows in the dataframe

ValueError: Length of values does not match length of index

In [76]:
len(df7.index)

6

In [77]:
df7

,ID,City,State,Country,Name,Employees
Address,,,,,,
3666 21st St,1,San Francisco,CA 94114,USA,Madeira,8
735 Dolores St,2,San Francisco,CA 94119,USA,Bready Shop,15
332 Hill St,3,San Francisco,California 94114,USA,Super River,25
3995 23rd St,4,San Francisco,CA 94114,USA,Ben's Shop,10
1056 Sanchez St,5,San Francisco,California,USA,Sanchez,12
551 Alvarado St,6,San Francisco,CA 94114,USA,Richvalley,20

In [78]:
#-------------------------------------------------------------------------------------
# Will give error - need to pass a list with exact number of rows in the dataframe
#-------------------------------------------------------------------------------------
df7["Continent"] = ["North America", "North America", "North America", "North America", "North America", "North America"]

In [79]:
df7

,ID,City,State,Country,Name,Employees,Continent
Address,,,,,,,
3666 21st St,1,San Francisco,CA 94114,USA,Madeira,8,North America
735 Dolores St,2,San Francisco,CA 94119,USA,Bready Shop,15,North America
332 Hill St,3,San Francisco,California 94114,USA,Super River,25,North America
3995 23rd St,4,San Francisco,CA 94114,USA,Ben's Shop,10,North America
1056 Sanchez St,5,San Francisco,California,USA,Sanchez,12,North America
551 Alvarado St,6,San Francisco,CA 94114,USA,Richvalley,20,North America

In [82]:
#----------------------------------------------------
#  Shape - number of rows and columns of dataframe
#          shape[0] = Number of rows
#          shape[1] = Number of columns
#----------------------------------------------------
df7.shape

(6, 7)

In [81]:
df7.shape[0]

6

In [83]:
df7["Continent"]=df7["Country"] + ", " + "North America"
df7

,ID,City,State,Country,Name,Employees,Continent
Address,,,,,,,
3666 21st St,1,San Francisco,CA 94114,USA,Madeira,8,"USA, North America"
735 Dolores St,2,San Francisco,CA 94119,USA,Bready Shop,15,"USA, North America"
332 Hill St,3,San Francisco,California 94114,USA,Super River,25,"USA, North America"
3995 23rd St,4,San Francisco,CA 94114,USA,Ben's Shop,10,"USA, North America"
1056 Sanchez St,5,San Francisco,California,USA,Sanchez,12,"USA, North America"
551 Alvarado St,6,San Francisco,CA 94114,USA,Richvalley,20,"USA, North America"

In [84]:
#----------------------------------------------------------
#  Transpose a datafram
#----------------------------------------------------------
df7_t = df7.T
df7_t

Address,3666 21st St,735 Dolores St,332 Hill St,3995 23rd St,1056 Sanchez St,551 Alvarado St
ID,1,2,3,4,5,6
City,San Francisco,San Francisco,San Francisco,San Francisco,San Francisco,San Francisco
State,CA 94114,CA 94119,California 94114,CA 94114,California,CA 94114
Country,USA,USA,USA,USA,USA,USA
Name,Madeira,Bready Shop,Super River,Ben's Shop,Sanchez,Richvalley
Employees,8,15,25,10,12,20
Continent,"USA, North America","USA, North America","USA, North America","USA, North America","USA, North America","USA, North America"

In [87]:
#-------------------------------------------------------------------------------------------
#  Use the transposed dataframe to add a new column to it
#-------------------------------------------------------------------------------------------
df7_t["My Address"]=[7, "My City", "My State", "My Country", "My Shop", 10, "My Continent" ]
df7_t

Address,3666 21st St,735 Dolores St,332 Hill St,3995 23rd St,1056 Sanchez St,551 Alvarado St,My Address
ID,1,2,3,4,5,6,7
City,San Francisco,San Francisco,San Francisco,San Francisco,San Francisco,San Francisco,My City
State,CA 94114,CA 94119,California 94114,CA 94114,California,CA 94114,My State
Country,USA,USA,USA,USA,USA,USA,My Country
Name,Madeira,Bready Shop,Super River,Ben's Shop,Sanchez,Richvalley,My Shop
Employees,8,15,25,10,12,20,10
Continent,"USA, North America","USA, North America","USA, North America","USA, North America","USA, North America","USA, North America",My Continent

In [88]:
#-------------------------------------------------------------------------------------------
#  Transpose the 'transposed' dataframe back and it will be the dataframe with the add row
#-------------------------------------------------------------------------------------------
df7 = df7_t.T  
df7

,ID,City,State,Country,Name,Employees,Continent
Address,,,,,,,
3666 21st St,1,San Francisco,CA 94114,USA,Madeira,8,"USA, North America"
735 Dolores St,2,San Francisco,CA 94119,USA,Bready Shop,15,"USA, North America"
332 Hill St,3,San Francisco,California 94114,USA,Super River,25,"USA, North America"
3995 23rd St,4,San Francisco,CA 94114,USA,Ben's Shop,10,"USA, North America"
1056 Sanchez St,5,San Francisco,California,USA,Sanchez,12,"USA, North America"
551 Alvarado St,6,San Francisco,CA 94114,USA,Richvalley,20,"USA, North America"
My Address,7,My City,My State,My Country,My Shop,10,My Continent

#### Modifying data in a column

In [89]:
#-------------------------------------------------------------------------------------------
#  Use the transposed dataframe to modify an exising column in it
#-------------------------------------------------------------------------------------------
df7_t["332 Hill St"]=[7, "My City2", "My State2", "My Country2", "My Shop2", 100, "My Continent2" ]
df7_t

Address,3666 21st St,735 Dolores St,332 Hill St,3995 23rd St,1056 Sanchez St,551 Alvarado St,My Address
ID,1,2,7,4,5,6,7
City,San Francisco,San Francisco,My City2,San Francisco,San Francisco,San Francisco,My City
State,CA 94114,CA 94119,My State2,CA 94114,California,CA 94114,My State
Country,USA,USA,My Country2,USA,USA,USA,My Country
Name,Madeira,Bready Shop,My Shop2,Ben's Shop,Sanchez,Richvalley,My Shop
Employees,8,15,100,10,12,20,10
Continent,"USA, North America","USA, North America",My Continent2,"USA, North America","USA, North America","USA, North America",My Continent

In [90]:
#-------------------------------------------------------------------------------------------
#  Transpose the 'transposed' dataframe back and it will be the dataframe with the add row
#-------------------------------------------------------------------------------------------
df7 = df7_t.T  
df7

,ID,City,State,Country,Name,Employees,Continent
Address,,,,,,,
3666 21st St,1,San Francisco,CA 94114,USA,Madeira,8,"USA, North America"
735 Dolores St,2,San Francisco,CA 94119,USA,Bready Shop,15,"USA, North America"
332 Hill St,7,My City2,My State2,My Country2,My Shop2,100,My Continent2
3995 23rd St,4,San Francisco,CA 94114,USA,Ben's Shop,10,"USA, North America"
1056 Sanchez St,5,San Francisco,California,USA,Sanchez,12,"USA, North America"
551 Alvarado St,6,San Francisco,CA 94114,USA,Richvalley,20,"USA, North America"
My Address,7,My City,My State,My Country,My Shop,10,My Continent

#### Real word use - convert address got geo coordinates

In [92]:
from geopy.geocoders import ArcGIS
nom = ArcGIS()

In [93]:
nom.geocode("3995 23rd St, San Francisco, CA 94114")

Location(3995 23rd St, San Francisco, California, 94114, (37.75292200397371, -122.43169700840102, 0.0))

In [94]:
n=nom.geocode("3995 23rd St, San Francisco, CA 94114")

In [95]:
type(n)

geopy.location.Location

In [96]:
df=pd.read_csv(csv_file)
df

,ID,Address,City,State,Country,Name,Employees
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [99]:
df["Full Address"]=df["Address"] + ", " + df["City"] + ", " + df["State"] + ", " + df["Country"]
df

,ID,Address,City,State,Country,Name,Employees,Full Address
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8,"3666 21st St, San Francisco, CA 94114, USA"
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15,"735 Dolores St, San Francisco, CA 94119, USA"
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25,"332 Hill St, San Francisco, California 94114, USA"
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10,"3995 23rd St, San Francisco, CA 94114, USA"
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12,"1056 Sanchez St, San Francisco, California, USA"
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20,"551 Alvarado St, San Francisco, CA 94114, USA"

In [102]:
df["Coordinates"]=df["Full Address"].apply(nom.geocode)
df

,ID,Address,City,State,Country,Name,Employees,Full Address,Coordinates
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8,"3666 21st St, San Francisco, CA 94114, USA","(3666 21st St, San Francisco, California, 9411..."
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15,"735 Dolores St, San Francisco, CA 94119, USA","(735 Dolores St, San Francisco, California, 94..."
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25,"332 Hill St, San Francisco, California 94114, USA","(332 Hill St, San Francisco, California, 94114..."
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10,"3995 23rd St, San Francisco, CA 94114, USA","(3995 23rd St, San Francisco, California, 9411..."
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12,"1056 Sanchez St, San Francisco, California, USA","(1056 Sanchez St, San Francisco, California, 9..."
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20,"551 Alvarado St, San Francisco, CA 94114, USA","(551 Alvarado St, San Francisco, California, 9..."

In [103]:
df.Coordinates[0]

Location(3666 21st St, San Francisco, California, 94114, (37.756648011392286, -122.42937496976432, 0.0))

In [108]:
df.Coordinates[0].latitude

37.756648011392286

In [109]:
df.Coordinates[0].longitude

-122.42937496976432

In [111]:
#-------------------------------------------------------------------------------
#  Need to appy lambda function to set latitude and longitude columns
#-------------------------------------------------------------------------------
df["Latitude"]=df["Coordinates"].apply(lambda x: x.latitude if x != None else None)
df["Longitude"]=df["Coordinates"].apply(lambda x: x.longitude if x != None else None)
df

,ID,Address,City,State,Country,Name,Employees,Full Address,Coordinates,Latitude,Longitude
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8,"3666 21st St, San Francisco, CA 94114, USA","(3666 21st St, San Francisco, California, 9411...",37.756648,-122.429375
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15,"735 Dolores St, San Francisco, CA 94119, USA","(735 Dolores St, San Francisco, California, 94...",37.757819,-122.425337
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25,"332 Hill St, San Francisco, California 94114, USA","(332 Hill St, San Francisco, California, 94114...",37.755875,-122.428816
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10,"3995 23rd St, San Francisco, CA 94114, USA","(3995 23rd St, San Francisco, California, 9411...",37.752922,-122.431697
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12,"1056 Sanchez St, San Francisco, California, USA","(1056 Sanchez St, San Francisco, California, 9...",37.752131,-122.430028
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20,"551 Alvarado St, San Francisco, CA 94114, USA","(551 Alvarado St, San Francisco, California, 9...",37.753511,-122.433229

In [110]:
#-------------------------------------------------------------------------------
#  Need to appy lambda function to set latitude and longitude columns
#  Note: Without Lambda function you get this error
#-------------------------------------------------------------------------------
df["Latitude"]=df["Coordinates"].latitude
df

AttributeError: 'Series' object has no attribute 'latitude'